import { SATSPERBITCOIN } from "./math";
const PAYMENT_DESCRIPTION = "Blitz Point-of-sale";
const ACCOUNT_LOCAL_STORAGE = "Account";
const SERVER_LOCAL_STORAGE = "Server_name";

export {
  SATSPERBITCOIN,
  PAYMENT_DESCRIPTION,
  ACCOUNT_LOCAL_STORAGE,
  SERVER_LOCAL_STORAGE,
};
