name: "[CI] React"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # `workflow_dispatch` allows to run the workflow manually
  # when selecting it in the `Actions tab`
  workflow_dispatch:

jobs:
  ci:
    - name: Run eslint
      run: |
        set -euxo pipefail
        yarn lint
